### ISSUE TITLE
CodaLab Submission Error

### ISSUE THREAD

**Issue by vateye** [jayleicn/moment_detr#1]
Hi, I recently generate the test results and validation results on CodaLab as the following structure.

```
--Submit.zip
----hl_val_submission.jsonl
----hl_test_submission.jsonl
```
The CodaLab gave me the error `IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmphfqu8Q/run/input/res/hl_test_submission.jsonl'`

How can I solve this problem?

**Comment by jayleicn** [comment]
Hi @vateye, Did you have an enclosing directory for these two files? The eval script expects no directory for the files.

**Comment by vateye** [comment]
> Hi @vateye, Did you have an enclosing directory for these two files? The eval script expects no directory for the files.

Yes, I just place the two files under `res` folder, and use `zip -r submission.zip ./res/*` to pack the files.

**Comment by jayleicn** [comment]
There is no need to place them under `res`, this `res` is an internal dir used by CodaLab. Select the two files directly and zip them.
