### ISSUE TITLE
About File missing in run_on_video

### ISSUE THREAD

**Issue by lmfethan** [jayleicn/moment_detr#12]
Thank you for your wonderful work!
However, when I tried to run your demo in folder run_on_video, the file bpe_simple_vocab_16e6.txt.gz for the tokenizer is missing.
Can you provide this file?

FileNotFoundError: [Errno 2] No such file or directory: 'moment_detr/run_on_video/clip/bpe_simple_vocab_16e6.txt.gz'

**Comment by jayleicn** [comment]
Thanks for reporting this issue, file added in a8c45bc.
