### ISSUE TITLE
How do I make my dataset ？

### ISSUE THREAD

**Issue by angaiei007** [jayleicn/moment_detr#14]
Hi, Congrats on the amazing work.   I want to make a data set similar to QVHighlights in my research direction, I have a lot of questions？
     1、What annotation tools do you use?  And details in the annotation process.
     2、How to use CLIP to extract QVHIGHLIGHTS text features ?   Can you provide the specific code？

**Comment by jayleicn** [comment]
Hi @angaiei007, we have detailed instructions in the supplementary file of the paper. For the tool, we use Amazon Mechanical Turk.
