### ISSUE TITLE
Video feature extraction

### ISSUE THREAD

**Issue by fxqzb** [jayleicn/moment_detr#17]
Hi, thanks for your excellent work! I found that the provided video features include both clip_features and slow_fast features. When it comes to the run_on_video/run.py, the codes only extract the clip features. Is there a mistake here? Besides, could you please provide the run.py extracting both clip and slowfast features? Thank you.

**Comment by jayleicn** [comment]
Hi @fxqzb, 

This is by design. Since CLIP feature extractor is quite easy to set up, while slowfast requires more dependencies. We don't have plans to provide one with both extractors. 

Best,
Jie

**Comment by fxqzb** [comment]
> This is by design. Since CLIP feature extractor is quite easy to set up, while slowfast requires more dependencies. We don't have plans to provide one with both extractors.

Got it. Thank you for your quick reply!
