### ISSUE TITLE
Slowfast config setting

### ISSUE THREAD

**Issue by QinghongLin** [jayleicn/moment_detr#19]
Hi, thanks for your good work and released code!

I have a question regarding the feature extractor:
which setting did you adopt for the QVHighlight slowfast feature? e.g., `SLOWFAST_8x8_R50`.

Thanks!

Kevin

**Comment by jayleicn** [comment]
We used the default `SLOWFAST_8x8_R50` as in https://github.com/linjieli222/HERO_Video_Feature_Extractor/blob/main/slowfast/extract_feature/extract.py#L36.
