### ISSUE TITLE
Experiments on Charades-STA dataset

### ISSUE THREAD

**Issue by minjoong507** [jayleicn/moment_detr#22]
Hi there, thanks for sharing your great work!

Following issues #11 and #8, I'm trying to train the model on Charades-STA.

However, I got the error message 'raise ValueError("Sample larger than population or is negative")'.

I think that the model cannot sample the negative clips because some gt moments are covering the entire video. 

https://github.com/jayleicn/moment_detr/blob/1e67364fb55c9a74b08a3e02824adfea622adb94/moment_detr/start_end_dataset.py#L104-L117

Thanks.

**Comment by onlyonewater** [comment]
when I train the model on the charades-sta dataset, I meet the same error, have you solved it?

**Comment by minjoong507** [comment]
Hi @onlyonewater 

Actually, it's been a while since I solved this problem. So I don't remember exactly what caused this problem.

In Charades-STA, some noisy annotations have longer moment length than video duration.

I'm not sure, but these cases may arise the problem because you can't sample negative clips from them.
