### ISSUE TITLE
Maximum video length

### ISSUE THREAD

**Issue by nguyenquyem99dt** [jayleicn/moment_detr#27]
First of all, I thank you for your contribution to the community.
Can you explain why the MomentDETR only supports the video up to 150s? When I comment `run_on_video/run.py, L:41`, it still works.

**Comment by jayleicn** [comment]
Hi @nguyenquyem99dt, Thanks for your appreciation. The model is only trained with data <=150s, there is no performance guarantee for videos longer than that. However, the model might be general enough to be extended to longer videos.

**Comment by nguyenquyem99dt** [comment]
Thank you for your explanation!
