### ISSUE TITLE
[Request for the approval in competition] Can you approve the request? Thanks.

### ISSUE THREAD

**Issue by EdenGabriel** [jayleicn/moment_detr#28]
Hello.

Thanks for the great work.
Motivated by the work and the interesting topic, we sincerely hope to get approved to be in the competition. (user name:Jin_Yang)

Thank you!!!
Btw, Sorry for bothering you.

Regards.

**Comment by jayleicn** [comment]
Hi @EdenGabriel, Your request is approved. Good luck! -- Jie
