### ISSUE TITLE
Request for the competition in codalab

### ISSUE THREAD

**Issue by sagileo** [jayleicn/moment_detr#47]
Hi, I sent a request to your competition in codalab. May you have a look at it? My username is old_tz.
[competition link](https://codalab.lisn.upsaclay.fr/competitions/6937#participate)

**Comment by jayleicn** [comment]
Hi @sagileo, It should have been approved already. Please check, thanks!

**Comment by sagileo** [comment]
Hi, I see that my request for participation has been denied and privileges have been suspended, according to the website. Can you check that?

**Comment by jayleicn** [comment]
I think you may have applied twice using different names. I approved the one with `Young_tz`.
