### ISSUE TITLE
Original Videos?

### ISSUE THREAD

**Issue by wjn922** [jayleicn/moment_detr#5]
Hi,

Where could we find the original videos? Thanks!

**Comment by jayleicn** [comment]
Hi @wjn922, You should be able to download the videos on from YouTube using tools such as https://github.com/ytdl-org/youtube-dl

**Comment by wjn922** [comment]
OK. Thanks.

**Comment by xljh0520** [comment]
> Hi @wjn922, You should be able to download the videos on from YouTube using tools such as https://github.com/ytdl-org/youtube-dl

Hi, I found that some videos are private and unable to download. Could you share your origin videos copy ？Thanks！
