### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by BMEI1314** [jayleicn/moment_detr#6]
hi,
  We think that mdetr has great potential, but we look at table 6 in the paper and find that the metics of moment retrieval on the charades-sta dataset is not much higher than that of ivg-dcl (in particular, ivg-dcl adopts C3d feature for video extractor and glove for text embedding), and your work uses clip feature + slowfast). Have you ever tested on other video grounding dataset, like activitynets?

**Comment by tony2016uestc** [comment]
我已经收到您的邮件，将尽快回复。

**Comment by jayleicn** [comment]
Hi @BMEI1314, in our work, we primarily focus on collecting the QVHighlights dataset and developing the MomentDETR model on top of this collected dataset. On CharadesSTA, we did not quite tune the model, but we still notice significant performance improvement (e.g., +3 on R1@0.5, or +5 with pretraining). We did not test on other datasets.

**Comment by BMEI1314** [comment]
Thanks for your quick reply and look forward to your follow-up work
