### ISSUE TITLE
The meaning of "tef"

### ISSUE THREAD

**Issue by vateye** [jayleicn/moment_detr#7]
Hi, I have a question about the "tef" in vision feature:
```python
if self.use_tef:
    tef_st = torch.arange(0, ctx_l, 1.0) / ctx_l
    tef_ed = tef_st + 1.0 / ctx_l
    tef = torch.stack([tef_st, tef_ed], dim=1)  # (Lv, 2)
    if self.use_video:
        model_inputs["video_feat"] = torch.cat(
            [model_inputs["video_feat"], tef], dim=1)  # (Lv, Dv+2)
    else:
        model_inputs["video_feat"] = tef
```

What does "tef" mean in the visual feature? Thanks in advance.

**Comment by jayleicn** [comment]
Hi @vateye, it is the temporal endpoint feature described in https://arxiv.org/pdf/1708.01641.pdf. It acts similar to positional embeddings to indicate the temporal position of each video feature.
