### ISSUE TITLE
Training on Charades-STA

### ISSUE THREAD

**Issue by vateye** [jayleicn/moment_detr#8]
Is is possible to release the training code on Charades-STA (codes related to load the dataset) as stated in the paper? Thanks.

**Comment by jayleicn** [comment]
Hi @vateye, we use the same data loader for charades-STA, but simply convert the dataset annotations into the same format as QVHighlights.

**Comment by vateye** [comment]
Hi @jayleicn, thanks for your reply. And I want to know how do you prepare the features? Did you extracted features by yourself with 2 seconds per clip?

**Comment by vateye** [comment]
Thanks.
